sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.pash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - docker build -f Dockerfile.dev -t kuuseorg/docker-demo .

script:
  - docker run kuuseorg/docker-demo npm run test

deploy:
  -
