apiVersion: certmanger.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-churnics-com-tls
spec:
  secretName: k8s-churnics-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.churnics.com
  dnsNames:
    - k8s.churnics.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.churnics.com
